### ISSUE TITLE
Blockwise support

### ISSUE THREAD

**Issue by ttajmaje** [Tanganelli/CoAPthon#10]
Would you be able to implement blockwise transfers in near future ?
From all python 2.x CoAP implementations, this one seems to be the best, but I would really appreciate blockwise support.

Thanks!

**Comment by Tanganelli** [comment]
Hi,
yes I plan to add blockwise, as well as other cool features, by the end of
March.

BR,
Giacomo

2015-02-18 15:10 GMT+01:00 ttajmaje <notifications@github.com>:

**Comment by Tanganelli** [comment]
Hi, the blockwise feature has been added to the current implementation. Any comments will be appreciated.
