### ISSUE TITLE
CoAPthon stop responding when server is down

### ISSUE THREAD

**Issue by dimasAdityamurthi** [Tanganelli/CoAPthon#100]
Hi,

I recently has installed CoAPthon in my RPi running on raspbian Strech.
I follow the instruction in "Install instruction" and I have successfully call my CoAP server and get the response. But when I try negative testing by calling wrong IP CoAP server, my RPi just freeze and it returns "No handlers could be found for logger "coapthon.client.coap"". What did I do wrong? Is there any steps that I miss?

Thank you all.

**Comment by Tanganelli** [comment]
Hi, I don't think that you miss something, I think it could be a bug in the client module. Where do you run the client? On the rasperry Pi or on another host? Anyway could you try to install the master branch?

**Comment by Tanganelli** [comment]
If you try with the master not it should be fixed.
