### ISSUE TITLE
No handlers could be found for logge

### ISSUE THREAD

**Issue by stephenwebb97** [Tanganelli/CoAPthon#103]
I'm getting this error "No handlers could be found for logger "coapthon.layers.messagelayer""
with this code:
client = HelperClient(server=(host, port))
	print "Call Back"
	t = time.time()
	if GPIO.input(4):
		# Rising Edge
		message = message_creator(1,t)
		print "test123",message
		message = encryption_suite.encrypt(message)
		# message = encrypt(password, message)
		print "encrypt",message

		print "Uncypt",encryption_suite2.decrypt(message)
		response = client.put(path,message)
		print "Just Sent on rise"
	else:
		# Falling edge
		response = client.put(path,message)
		print "Just Sent on the fall",t

and I dont know why? (I'm using it on a raspberry PI where this is called as a call back function)

Thanks heaps

**Comment by Tanganelli** [comment]
Now it is fixed.
