### ISSUE TITLE
Issues with collect server?

### ISSUE THREAD

**Issue by nzfarmer** [Tanganelli/CoAPthon#118]
HI

Am trying to get a crude observable example working.  Have come across two potential issues:

1. the example starts a timer in read_sensor then invokes self._coap.server.notify

This ends up in a recursive loop as notify calls read_sensor, as does the Timer

2.  When a RST (Reset) is received the Resource is not notified to end the timer.

**Comment by Tanganelli** [comment]
Please do not use the collectserver. It has been designed for a specific use case and it does not work.
