### ISSUE TITLE
How to setup a CoAP server to listen only few paths

### ISSUE THREAD

**Issue by dcomins** [Tanganelli/CoAPthon#124]
Hi,

I have set up a basic resource CoAP Server, this is the code below:

![image](https://user-images.githubusercontent.com/20353282/47501359-a1a45c80-d865-11e8-8739-f8ac0f6dedd8.png)

The problem is that I can not differenciate the message sent from the clients in different paths, I receive in render_POST() callback all message aunque they have been sent from different paths.

How can I differenciate so the message sent from different paths in my CoAP Server?

**Comment by Tanganelli** [comment]
Sorry but I do not understand. With the attached code the CoAP server will
serve all request for the "/basic" path. Other paths will result in a NOT
FOUND error.

Il giorno gio 25 ott 2018 alle ore 14:53 dcomins <notifications@github.com>
ha scritto:

**Comment by dcomins** [comment]
My question is for example if I add another path (/temp) to my CoAP Server (self.add_resource('temp/', BasicResource()) how can I know if a message received in render_POST() callback comes from /temp path or /basic path?

**Comment by Tanganelli** [comment]
Ok now I understand. You should create another resource with its render
post method. However, there is also another solution, you can use the
render_post_advanced which receives in input the request object, than you
can check the request.uri_path property.

Il gio 25 ott 2018, 20:20 dcomins <notifications@github.com> ha scritto:
