### ISSUE TITLE
[Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by dcomins** [Tanganelli/CoAPthon#134]
Hello,

At this point I am able to detect 4 nodes with an IPv6 command from my Raspberry Pi (I have IPv6 connection with them). Nevetheless when I request a GET command to my 4 nodes with the CoAPthon library, I get response from 3 nodes but when I request GET to the last node I receive this error and my python script gets stucked. What is the error that I receive? How can I solve it?

![image](https://user-images.githubusercontent.com/20353282/50290822-2af29c80-046d-11e9-88be-ae50c5d06698.png)

**Comment by Tanganelli** [comment]
Are you using client or server? How did you start them? Can you ping the
address of the last node?

Il giorno gio 20 dic 2018 alle ore 15:39 dcomins <notifications@github.com>
ha scritto:

**Comment by dcomins** [comment]
I am using a CoAPthon python client to request GET to my nodes. My nodes have a CoAP server and client into them to receive the requests. I am able to ping all the address of my 4 nodes as you can see here.

These are the 4 nodes addresses:

![image](https://user-images.githubusercontent.com/20353282/50341072-b6c40180-051d-11e9-8771-467243d629fc.png)

And here I ping the 4 addresses:

![image](https://user-images.githubusercontent.com/20353282/50341084-c6dbe100-051d-11e9-890c-6f3204939ab4.png)

![image](https://user-images.githubusercontent.com/20353282/50341094-cfccb280-051d-11e9-8c93-706afb41ba80.png)

**Comment by dcomins** [comment]
Ok, solved. I realized I used a bad IPv6 when I made the requests. So I obtained Network is unreachable.
