### ISSUE TITLE
Implement DTLS support

### ISSUE THREAD

**Issue by evnm** [Tanganelli/CoAPthon#14]
I'm interested in using a Python CoAP client library for a project that requires security. I happened upon this library and was pleased to see recent activity. Is there a likely timeframe for implementing DTLS support?

**Comment by Tanganelli** [comment]
Hi,
It is in our TODO list, and I hope we will provide DTLS support in few
months.


2015-04-23 19:57 GMT+02:00 Evan Meagher <notifications@github.com>:

**Comment by louisZL** [comment]
When would provide DTLS support?

**Comment by rsweis62** [comment]
Is DTLS going to happen anytime soon?

**Comment by stevecalvert** [comment]
Hi Giacomo, I'm also interested in DTLS support - would really appreciate an update on this

**Comment by Venkat2811** [comment]
Hi @Tanganelli ,

Update on DTLS support would be much appreciated !

Thanks,
Venkat

**Comment by Tanganelli** [comment]
Hi all,
I know that everybody would like DTLS. However it is a real long work in my opinion, thus I would really appreciate if someone could help me on this.

**Comment by shantanoo-desai** [comment]
This Repository for [DTLS](https://github.com/rbit/pydtls) seems promising if this needs to be done @Tanganelli

**Comment by jyotirajsharma** [comment]
Hi,
I am trying to use this library. Does it support DTLS now ??

**Comment by Tanganelli** [comment]
Now it should support DTLS, however I still have to evaluate it.

**Comment by jyotirajsharma** [comment]
Could you please help to provide example script ? I am able to send coap from my Pi3 to node.js coap server via Python Shell. I used coapclient.py as I need client side only.

**Comment by mcfreis** [comment]
Maybe you should have a look at test_secure.py which is all about examples on using DTLS with CoAPthon, especially function test_ok_with_handshake_on_connect() and try modifying "your version" of coapclient.py to meet your needs. Basically it is only creating a DTLS socket and giving it to HelperClient() on creation.

**Comment by jyotirajsharma** [comment]
Thank you for your response.
Is there any other method to install Dtls ? I am not able to install Dtls via "pip install Dtls" command.

**Comment by jyotirajsharma** [comment]
Thank you for your response.

I am getting following error while trying to execute test_secure.py. I have already installed pip install Dtls though. Please help to resolve this.

Traceback (most recent call last):
  File "test_secure.py", line 23, in <module>
    from dtls.wrapper import wrap_server, wrap_client
  File "/usr/local/lib/python2.7/dist-packages/dtls/__init__.py", line 63, in <module>
    from patch import do_patch
  File "/usr/local/lib/python2.7/dist-packages/dtls/patch.py", line 44, in <module>
    from sslconnection import SSLConnection, PROTOCOL_DTLS, PROTOCOL_DTLSv1, PROTOCOL_DTLSv1_2
  File "/usr/local/lib/python2.7/dist-packages/dtls/sslconnection.py", line 60, in <module>
    from x509 import _X509, decode_cert
  File "/usr/local/lib/python2.7/dist-packages/dtls/x509.py", line 34, in <module>
    from openssl import *
  File "/usr/local/lib/python2.7/dist-packages/dtls/openssl.py", line 811, in <module>
    ((c_char_p, "ret"), (c_int, "nid")), True, None),
  File "/usr/local/lib/python2.7/dist-packages/dtls/openssl.py", line 642, in <lambda>
    map(lambda x: _make_function(*x), (
  File "/usr/local/lib/python2.7/dist-packages/dtls/openssl.py", line 562, in _make_function
    for i in args[1:]))
AttributeError: /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0: undefined symbol: DTLS_server_method

**Comment by jyotirajsharma** [comment]
How to install Openssl1.0.2 version in Debian (Raspberry Pi3) OS ?
It just installs OpenSSL1.0.1 automatically. I require version later than this i.e. 1.0.2* which supports DTLS.

I installed openssl1.0.2g from some site but it does not link lib dynamically as I could not see 'libssl.1.0.0' when I run this command '$ ldd /usr/bin/openssl'

**Comment by Tanganelli** [comment]
Hi, take a look to: [https://raspberrypi.stackexchange.com/questions/66782/how-to-install-openssl-1-0-2-on-raspberry-pi3/67045](https://raspberrypi.stackexchange.com/questions/66782/how-to-install-openssl-1-0-2-on-raspberry-pi3/67045)
