### ISSUE TITLE
Server non può fare il join in gruppi differenti (defines.ALL_COAP_NODES)

### ISSUE THREAD

**Issue by TheLoader** [Tanganelli/CoAPthon#15]
Ciao Giacomo,

siamo due tesisti che studiano il CoAP(ti avevamo già contattato in precedenza via email) e stiamo utilizzando la tua implementazione. Per il nostro progetto abbiamo modificato il file coapthon/server/coap_protocol.py in quanto non rendeva possibile al server il join a gruppi differenti da quello da te definito in defines.ALL_COAP_NODES. Abbiamo risolto implementando una funzione che permettesse di scegliere il gruppo appena istanziato e cambiando di conseguenza il parametro in ingresso alla funzione di join:

# Funzione definita :
def setGroup(self,g):
        self.group = g

# Riga 79 del medesimo file
self.transport.joinGroup(self.group)

Facci sapere cosa ne pensi, o se quanto da te fatto era una semplice scelta progettuale.

**Comment by Tanganelli** [comment]
Ciao,
si potrebbe essere una buona scelta. Tuttavia fate una pull request cosi` controllo meglio ed eventualmente integro la vostra modifica.
