### ISSUE TITLE
Integer CoAP options are not handled correctly

### ISSUE THREAD

**Issue by kuggenhoffen** [Tanganelli/CoAPthon#17]
Trying to deserialize a CoAP message with content-type option like so:

```python
from coapthon.messages.request import Request
from coapthon.messages.option import Option
from coapthon import defines
from coapthon.serializer import Serializer

r = Request()
r.mid = 0
r.code = defines.inv_codes["GET"]
r.type = defines.inv_types["CON"]
opt = Option()
opt.number = defines.inv_options["Content-Type"]
opt.value = defines.inv_content_types["text/plain"]
r.add_option(opt)

ser = Serializer()
bytes = ser.serialize(r)
msg = ser.deserialize(bytes, None, None)
```
Results in TypeError:
`
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    msg = ser.deserialize(bytes, None, None)
  File "/home/jaakuk03/Development/CoAPthon/coapthon/serializer.py", line 99, in deserialize
    value = (value << 8) | b
TypeError: unsupported operand type(s) for |: 'int' and 'str'
`

**Comment by Tanganelli** [comment]
Hi, you are right. I think I make some mess between branches, I will fix it during the weekend.

**Comment by Tanganelli** [comment]
Hi, it should be fixed now. Thank you.
