### ISSUE TITLE
What Python version is required?

### ISSUE THREAD

**Issue by IanHarvey** [Tanganelli/CoAPthon#20]
I'm trying to find out which Python version this is targetted at. The 'print' statements suggest it's Python 2.x, but when I try running it (e.g. coapserver.py) it can't import 'concurrent.futures', which is a Python 3.x module. How can I get this to run?

Thanks
Ian

**Comment by Tanganelli** [comment]
Hi
as you supposed it is python 2.7, the concurrent.futures package has been ported to python 2.7, if you follow the installation instructions you will end with the concurrent.futures package installed through pip. 

Best
Giacomo
