### ISSUE TITLE
Support for RESTful resource URI

### ISSUE THREAD

**Issue by iamDecode** [Tanganelli/CoAPthon#23]
I am trying to implement a CoAP server that handles requests of the following format:

`GET /element`    to select all elements
`GET /element/:id`   e.g. /element/12 to select a specific element
`GET /element/:id/property`  to get a certain property of a specific element

Is there any way to do this with this library? I could not directly find support for such a thing.

**Comment by MarcoIeni** [comment]
modify the [coapserver.py](https://github.com/Tanganelli/CoAPthon/blob/master/coapserver.py) and modify the `self.add_resource` part with something like 

```python
self.add_resource('/element', MyResource1())
self.add_resource('/element/:id', MyResource1())
self.add_resource('/element/:id/property', MyResource1())
```

then modify [this](https://github.com/Tanganelli/CoAPthon/blob/b2073aadacd461440059520ae206cca152aeb27d/exampleresources.py) and add your resources. For example:

```python
class MyResource1(Resource):
    def __init__(self, name="MyResource1", coap_server=None):
        super(MyResource1, self).__init__(name, coap_server, visible=True,
                                            observable=True, allow_children=True)
        self.payload = "Basic Resource"
        self.resource_type = "rt1"
        self.content_type = "text/plain"
        self.interface_type = "if1"

    def render_GET(self, request):
        #your instructions here
        return self
```

**Comment by Tanganelli** [comment]
I think the fact is that CoAP has been designed for constrained devices not for implementing REST interfaces. Even if you can hack the code to obtain the wanted behavior I don't suggest to use CoAP.
