### ISSUE TITLE
incorrect handling of dublicate messages

### ISSUE THREAD

**Issue by mishindmitry** [Tanganelli/CoAPthon#25]
Hi kind sir,

Thank you for implementing this for Python, saved much time and headache.
I've noticed that if the default server listener is used, then the dublicate message is handled incorrectly - server sends response and returns from listen() and thus is stopped. I think there should be `continue` instead of `return`.

**Comment by Tanganelli** [comment]
Can you send a pull request, so I can test and accept it?

**Comment by Tanganelli** [comment]
Perfect thanks a lot
