### ISSUE TITLE
How to handle runtime errors

### ISSUE THREAD

**Issue by suraj-shingade** [Tanganelli/CoAPthon#29]
![errors](https://cloud.githubusercontent.com/assets/6264445/16708990/515e3d46-4621-11e6-9565-8965ebc01e85.png)

 def connect_server(self, message):
        try:
            print "\n + Preparing to connect."
            client = HelperClient(message.destination)

```
        print "\n + Observing start."
        if message is not None:
            print "\n + Connection established."
            received_message = client.send_request(message)
            print received_message
            if received_message:
                print "\n + Validating response."
                print received_message.mid
                print received_message.token
                print received_message.payload
            client.stop()
            print "\n + Connection Closed."
    except:
        print "Errors"
    finally:
        # Finally clause:
        print("Finally clause reached")
```

but not handling in errors

i am trying to handle server unavailability event .

**Comment by Tanganelli** [comment]
Hi, 
I'll go to add a timeout on the send_request. Server unavailability cannot be directly detect due to the fact that CoAP uses UDP.

**Comment by Tanganelli** [comment]
Now you can find a timeout parameters on all methods of the HelperClient function.
