### ISSUE TITLE
CoAPthons empty ACK echo token

### ISSUE THREAD

**Issue by maribu** [Tanganelli/CoAPthon#33]
When sending a GET request to URI path "/seperate" of the `coapserver.py` example using a `CON` message with a token, the empty `ACK` echos the token of the `CON` message. Correct would be to only echo the message ID and not sending a token.

In the [CoAP specification Section 2.2](https://tools.ietf.org/html/rfc7252#section-2.2) in figure 4 piggybacked responses are shown, where the ACK does contain a token (as it contains a response to match a request). In figure 5 a separate response is shown and the ACK does not contain a token, but the delayed response does.

Regards,
maribu

**Comment by Tanganelli** [comment]
Right. I have to correct this.

**Comment by Tanganelli** [comment]
I just correct such bug.
