### ISSUE TITLE
Serializer.deserialize restricted to handling of Integers and Strings

### ISSUE THREAD

**Issue by locomuco** [Tanganelli/CoAPthon#41]
using byte values in CoAP options can lead to conversion errors.

E.g. using the ETAG option which is considered to contain an OPAQUE content, is forced to be converted to a string which ends up in 

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

**Comment by Tanganelli** [comment]
Yes, you are totally right. I have to find a better way for that. If you want to contribute in such sense you are more than welcome :D

**Comment by Tanganelli** [comment]
Could you provide e an example of such behaviour? Because I think the problem is raised only when you try to print such parameters, but at least for the ETAG option everything works fine in my environment.

**Comment by danielwidmann** [comment]
This is a minimal testcase that shows the behavoir:
``` python
class SimpleTests(unittest.TestCase):

    def test_utf_deserialize(self):
        req = Request()
        req.type = defines.Types["CON"]
        req._mid = 1
        req.etag = bytearray([0xc5])

        serializer = Serializer()
        serialized = serializer.serialize(req)
        received_message = serializer.deserialize(serialized, ("127.0.0.1", 5683))

        self.assertEqual(req.etag, received_message.etag)
```

It fails with:

```
Error
Traceback (most recent call last):
  File "/home/daniel/coapthon/CoAPthon/tests.py", line 94, in test_utf_deserialize
    received_message = serializer.deserialize(serialized, ("127.0.0.1", 5683))
  File "/home/daniel/coapthon/CoAPthon/coapthon/serializer.py", line 95, in deserialize
    option.value = Serializer.convert_to_raw(current_option, value, option_length)
  File "/home/daniel/coapthon/CoAPthon/coapthon/serializer.py", line 281, in convert_to_raw
    return bytearray(value, "utf-8")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)
```
