### ISSUE TITLE
The re-transmission mechanism stops in case of block-wise POST for a lossy link  

### ISSUE THREAD

**Issue by abhijan79** [Tanganelli/CoAPthon#42]
We have investigated the problem. It seems that once one block is successfully transferred the message.acknowledged flag is set to true. However, as soon as a next block hits hits the timeout it does not enter the re-transmission logic.
Probably because the line #125 in client/coap.py:
`while retransmit_count < defines.MAX_RETRANSMIT and (not message.acknowledged and not message.rejected) \
 +                    and not self.stopped.isSet():`
the "message.acknowledged" is True due to the prior success of the earlier block. So, the loop is not actually entered and the client keeps waiting checking whether file descriptor was set rather then proactively setting the descriptor through re-sending the datagram.

**Comment by Tanganelli** [comment]
You are probably right. Did you try to modify how acknowledgment is set?
