### ISSUE TITLE
PUT response with payload

### ISSUE THREAD

**Issue by arauko9** [Tanganelli/CoAPthon#45]
First, thank you for this library.

I'm trying to get a PUT response with a payload, however I'm not able to do it, the response always comes with an empty payload. Is it possible to do so with this library?

Here is the relevant part of my code:

```
def render_PUT(self, request):
    if request.payload == "0":
        self.payload = "message 1"
    else:
        self.payload = "message 2"
   return self
```

**Comment by Tanganelli** [comment]
Hi, no it is not possible because CoAP does not allow it. Even if you can make some hack to do that, it violates the the REST design of CoAP.

**Comment by arauko9** [comment]
Sorry to insist, but I don't think that's quite right. Or maybe I'm understanding something wrong.  In the specificacion of CoAP, section 5.9.1.4[1], it says that 2.04 responses to PUT or POST request can have a payload. Besides, I'm testing different implementations of CoAP and all of them but CoAPthon are able to respond with 2.04 Changed responses with a payload to PUT requests.

[1]https://tools.ietf.org/html/rfc7252#section-5.9.1.4

**Comment by Tanganelli** [comment]
Well, you are right. I was really convinced about what I said but I was wrong. I will change this ASAP.

**Comment by Tanganelli** [comment]
Bug fixed.

**Comment by Tanganelli** [comment]
@arauko9 To allow to have a response with the payload and without, I added a new boolean parameters to the resource, which is called reply_payload. You can view the render_PUT method of the ETAG resource in the exampleresources.py.

**Comment by Tanganelli** [comment]
I would like to extend the interface of resources to handle this behavior in a cleaner way.

**Comment by Tanganelli** [comment]
Hi I definitely found time to enhance the resource's interface. Now a resource can be created also by the definition of render_GET_advanced, render_POST_advanced, render_PUT_advanced and render_DELETE_advanced. All this new methods have the same prototype:
```python
render_METHOD_advanced (self, request, response):
    ...
   return self, response
```

For details take a look to the AdvancedResource and the AdvancedResource separate in the `exampleresource.py`
