### ISSUE TITLE
Separate responses not working

### ISSUE THREAD

**Issue by amytennant** [Tanganelli/CoAPthon#46]
For a separate response to work there needs to be a token. The HelperClient only has a token for the Post method (not that it works because other code needs it to be lower case). 

I have attached a patch with changes to helperclient.py with the tokens added. The patch has also got changes to allow a timeout to be set through the helper methods. 
[CoAPthonHelper.zip](https://github.com/Tanganelli/CoAPthon/files/617412/CoAPthonHelper.zip)

**Comment by Tanganelli** [comment]
Hi, thanks for your work, I will add your part concerning the timeout ASAP. Regarding the token I would like to point out that an empty token is still a token. In other words, if you don't put explicitly a token it means that you are using the default null token. Thus there isn't any needs to explicitly add a token. At least that is my understanding from the CoAP RFC.

**Comment by Tanganelli** [comment]
I have just added your contribution.
