### ISSUE TITLE
Unable to get response from CoAP server

### ISSUE THREAD

**Issue by knighti** [Tanganelli/CoAPthon#52]
Hello, I have implemented the server as mention in read_me file. When i issue the start command via putty it gives be response as below:
![coapserver](https://cloud.githubusercontent.com/assets/12207616/23082442/30292b90-f57b-11e6-9ec8-5578a575bd99.jpg)
Now when i try to access this via Firefox plugin "Copper" it gives me no response.

_Can you please help me? What i actually want to do is to run a server with CoAP, so that all my iot devices can communicate via coap. Any help will be appreciated._

**Comment by Tanganelli** [comment]
Hi, which request do you issue in Copper? Maybe also a screenshot could help.
