### ISSUE TITLE
Installing CoAPthon through pip

### ISSUE THREAD

**Issue by Venkat2811** [Tanganelli/CoAPthon#54]
Hi @Tanganelli ,

Could you please publish CoAPthon to pip so that users can install it directly ?

Thanks,
Venkat

**Comment by Tanganelli** [comment]
Hi @Venkat2811, 
I already thought to it, however I would like to publish to pip when the DTLS support will be added. Anyway if you would like to install CoAPthon in your environment through pip the procedure is straightforward: 
```bash
$ git clone https://github.com/Tanganelli/CoAPthon.git
$ cd CoAPthon
$ python setup.py sdist
$ sudo pip install dist/CoAPthon-4.0.0.tar.gz -r requirements.txt
```
Best
Giacomo

**Comment by Venkat2811** [comment]
Hi @Tanganelli ,

Yes. It is straightforward.  We're developing automated agents and all our dependencies are installed through `pip`.  Compared to `txThings`, `CoAPthon` is rich in features.  The only thing that is currently stopping us is `pip`.  Could you please consider releasing a version without DTLS support? Would be a great value add to the community :)

Thanks,
Venkat.

**Comment by Tanganelli** [comment]
Hi @Venkat2811, ok I will publish it ASAP.

Best,
Giacomo

**Comment by Venkat2811** [comment]
Great ! Thank you @Tanganelli . Please let me know once you've published it

**Comment by Tanganelli** [comment]
Now it is on pip :+1:

**Comment by Venkat2811** [comment]
Great ! Thanks 👍
