### ISSUE TITLE
Generating documentation gives bitstring errors

### ISSUE THREAD

**Issue by christofferholmstedt** [Tanganelli/CoAPthon#6]
I followed the install instructions in the README and it all seemed to work but the bitstring package didn't install properly. I noticed this when generating documentation. Bitstring is mentioned in the requirements.txt file so it should have worked the first time around.

I just ran "sudo pip install bitstring" and it installed fine and now I can generate documentation properly. I will see if I get time to reproduce the installation error later on in a VM.

**Comment by claudyus** [comment]
I would also like to suggest to publish the documentation on readthedocs.org to increase accessibility

**Comment by Tanganelli** [comment]
Documentation added on readthedocs.org
