### ISSUE TITLE
does CoAP to HTTP proxy is up?

### ISSUE THREAD

**Issue by andaesa** [Tanganelli/CoAPthon#76]
I read on the documentation saying that CoAP to HTTP proxy is in the to do list. Is the development is still in progress?

**Comment by Tanganelli** [comment]
CoAP to HTTP yes, whereas HTTP to CoAP is already available.

BR
Giacomo

2017-05-15 7:19 GMT+02:00 andaesa <notifications@github.com>:

**Comment by andaesa** [comment]
oh, thanks. by the way I wanted to confirm since I am still new in understanding CoAP. Does CoAP to HTTP proxy here means that the request that came via CoAP protocol can be translate into HTTP request? Thank you

**Comment by Tanganelli** [comment]
Yes exactly.

2017-05-15 12:10 GMT+02:00 andaesa <notifications@github.com>:

**Comment by andaesa** [comment]
Thank you for your information. I am closing this issue now.
