### ISSUE TITLE
How do I make a resource observable and send notifications?

### ISSUE THREAD

**Issue by christofferholmstedt** [Tanganelli/CoAPthon#8]
I'm trying to configure a Resource to act as observable. "Observable" is set to true but how do I define/implement when to send the notifications? (I haven't found an example nor test that do this).

All resources inherite from coapthon2.resource.resource which has the _observable and _observe_count member variables. CoAP() has the functionality of notify() and prepare_notification() which seems useful but I don't really understand how all parts fit together at the moment and I might have too many moving targets trying to debug the server with Copper firefox plugin (sending observe messages that even wireshark can't dissect).

My best bet is to use prepare_notification() somehow but not sure how to properly create a thread (or use existing one) so I don't lock processing of incoming requests (looping in my render_GET() seems wrong).

**My questions**
1. Is Resource.Resource._observe_count the counter for number of clients that are observing that specific resource (default value of 1 doesn't make sense if that is the case)?
2. Generating the documentation for "layer.observe" gives some odd explanation. The "parameters" explanation for "notify" is the same as for "notify_deletion".
3. How do I define/implement when to send notifications?

**Comment by goslim12** [comment]
I was trying to carry out function of observe by changing value of payload to present time of BasicREsource after i saw what you answered. but it doesn't work what's wrong with it?(i tried to access from fitefox to coap) 



class BasicResource(Resource):
    def __init__(self, name="BasicResource", coap_server=None):
        super(BasicResource, self).__init__(name, coap_server, visible=True,
                                            observable=True, allow_children=True)
        self.payload = "basic"
        self.resource_type = "rt1"
        self.content_type = "text/plain"
        self.interface_type = "if1"

    def render_GET(self, request):
        self.payload = str(datetime.datetime.now())
        return self
