### ISSUE TITLE
Multicast and Non-Confirmable?

### ISSUE THREAD

**Issue by robbym** [Tanganelli/CoAPthon#98]
Is there a way to use the helper client to send out a multicast post that is non-confirmable?

**Comment by Tanganelli** [comment]
Yes of course, just use the multicast address and register the client in
the multicast group. Take a look at multicast.py

2017-11-01 0:13 GMT+01:00 robbym <notifications@github.com>:

**Comment by EmileAlbert** [comment]
Hello, 

I try to send multicast request. To do that I just replace IPv6 address with "ff02::1" but this does not send any request. Moreover I don't find the multcast.py mentioned in this issue. Did you commit any improve/change ? Do you have any idea of the issue ? 

Thanks in advance !
