### ISSUE TITLE
Does the library support python 3?

### ISSUE THREAD

**Issue by Pazhanivel** [Tanganelli/CoAPthon#99]
getting the following error run it in python 3

`D:\Pazhani\coap_\coapthonTest\CoAPthon-master>python coapclient.py
Traceback (most recent call last):
  File "coapclient.py", line 7, in <module>
    from coapthon.client.helperclient import HelperClient
  File "D:\Pazhani\coap_\coapthonTest\CoAPthon-master\coapthon\client\helperclie
nt.py", line 3, in <module>
    from Queue import Empty
ModuleNotFoundError: No module named 'Queue'`

but works in python 2.

is there a way to make it work in python 3?

**Comment by Tanganelli** [comment]
There is a specific branch for python 3 even if it is not totally aligned
with the master branch: https://github.com/Tanganelli/CoAPthon/tree/python3

2017-11-01 7:59 GMT+01:00 Pazhanivel <notifications@github.com>:

**Comment by Pazhanivel** [comment]
Thanks for the reply.
--------------------------------------
in python3 branch , I am getting many errors related to python2 - python3 conversion such as 
SyntaxError: Missing parentheses in call to 'print'

D:\Pazhani\coap_\CoAPthon-python3\CoAPthon-python3>python coapserver.py
Traceback (most recent call last):
  File "coapserver.py", line 5, in <module>
    from coapthon.server.coap import CoAP
  File "D:\Pazhani\coap_\CoAPthon-python3\CoAPthon-python3\coapthon\server\coap.
py", line 105
    print "Exception with Executor"
                                  ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by Tanganelli** [comment]
Ok I get the point, honestly I am really busy nowadays to try to make it work. Anyway you can download the python 2 code from the master branch and execute the 2to3 automatic python conversion tool: [https://docs.python.org/2/library/2to3.html](https://docs.python.org/2/library/2to3.html). 

BR
Giacomo

**Comment by Pazhanivel** [comment]
Thanks.
Will see if this works..

**Comment by hahahannes** [comment]
Hi @Pazhanivel,
I have a working fork that supports python3. I can upload my code, if you still need it. Later I will do a PR.

Best regards
Hannes

**Comment by wangnuannuan** [comment]
I need the library support python 3,where i can get it  @hahahannes

**Comment by Tanganelli** [comment]
@wangnuannuan if you which I created a specific repository for Python 3. https://github.com/Tanganelli/CoAPthon3
